### PR TITLE
Home Page #10

### PR DESCRIPTION
**Pull request by ankitminglani**
Home Page #10
 
fixed the error in console log where jquery was loaded after bootstrap and bootstrap was throwing error because jquery was not found.

Also fixed couple of alignment issues on home page

### CODE REVIEW

**Comment by ankitminglani** [comment]
Very slight spacing issue on left and right

Before:
Screenshot from 2020-10-24 00-47-49


After:
Screenshot from 2020-10-24 00-46-04

**Review by abhibhaw — CHANGES_REQUESTED** [review]
Hey @ankitminglani,

Thanks for sending your PR. This PR is a bit minor to add you as a contributor to our project. We will be really happy to see some UI changes from your side.

Kindly follow the following Contribution Guidelines:

- As there is already a linked issue #10 . Kindly get it assigned first if you are addressing it.
- If the issue doesn't exist beforehand, kindly create one.
- Don't forget to describe the changes in the comments, so that it will be easier for us to review.

**Comment by ankitminglani** [comment]
@abhibhaw I dont think it was closed by any bot, Aniket closed it without any comments. 
If i need to get something assigned something to me first, could you please enhance your contribution guidelines?
https://github.com/Webwiznitr/Project-daffodil/blob/main/README.md 

#10 mentioned **Make the UI of home page better** and that's what I did. I am contributing to github projects for the first time for hacktoberfest 2020. I am sorry but i see you have requested changes, are you expecting me to do more bigger changes in the project to merge my code?

**Comment by abhibhaw** [comment]
> @abhibhaw I dont think it was closed by any bot, Aniket closed it without any comments.
> If i need to get something assigned something to me first, could you please enhance your contribution guidelines?
> https://github.com/Webwiznitr/Project-daffodil/blob/main/README.md
> 
> #10 mentioned **Make the UI of home page better** and that's what I did. I am contributing to github projects for the first time for hacktoberfest 2020. I am sorry but I see you have requested changes, are you expecting me to do more bigger changes in the project to merge my code?

@ankitminglani Kindly read my comments again, I never said it was closed by any bot! I said it was marked as spam by our spammy bot! And any maintainer is supposed to close/review the spam marked PR.

And yes, due to hacktoberfest 2020 new guidelines, we can't promote very small changes as a valid hacktoberfest PR. Or, we fear our repo will be marked as invalid for hacktoberfest.

And, talking about the issue's assigning guidelines, it's a normal open source standard. And one of our member is already addressing it in #21 .

**Pull request closed without merging**
