### PR TITLE
Change in complete design

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Aniket762** [comment]
Hey @MayurJ-mike can you please share the screenshots of the changes you made.

**Comment by ghost** [comment]
Yeah, sure. I tried to make it better. Hope you like it. Take a look at it.


[screencapture-file-C-Users-HP-Desktop-projects-Project-daffodil-index-html-2020-10-24-12_39_48.pdf](https://github.com/Webwiznitr/Project-daffodil/files/5432532/screencapture-file-C-Users-HP-Desktop-projects-Project-daffodil-index-html-2020-10-24-12_39_48.pdf)
[screencapture-file-C-Users-HP-Desktop-projects-Project-daffodil-index-html-2020-10-24-12_40_11.pdf](https://github.com/Webwiznitr/Project-daffodil/files/5432533/screencapture-file-C-Users-HP-Desktop-projects-Project-daffodil-index-html-2020-10-24-12_40_11.pdf)

**Comment by sayna3311** [comment]
It would be better if you could make those many changes to the original version, so as to make it look more appealing.

**Comment by sayna3311** [comment]
It would be better @MayurJ-mike , if you could make those many changes to the original version, so as to make it look more appealing?

**Comment by ghost** [comment]
You can add whatever you want, in this version also. I thought I had to design a layout. So, I made this.

**Comment by ghost** [comment]
Looks like you didn't liked this design, Isn't it?

**Comment by sayna3311** [comment]
I prefer the original layout more. It would be great if you can do the changes to the original one.

**Comment by ghost** [comment]
We should close this pull request then......

**Pull request closed without merging**
